# Basic analyses for sample size reports - will rename if things get out of hand

#' @title Quick table for sample size estimation for change-from baseline
#' @param n \code{integer}. The sample size. Set to NULL to estimate
#' @param prec \code{numeric}. The precision. Set to NULL to estimate
#' @param sd1 \code{numeric}. The standard deviation of the first paired measurement
#' @param sd2 \code{numeric}. The standard deviation of the second paired measurement. 
#'   Defaults to NULL, which sets it equal to \code{sd1}
#' @param cor \code{numeric}. The correlation between sd1 and sd2
#' @param mean \code{numeric}. Hypothetical mean for confidence interval computation. 
#'     Set to 0 by default. 
#' @param conf_level \code{numeric}. Confidence level. 
#' @param ... Other arguments to \code{presize::prec_mean}
#' 
#' @export
prec_paireddiff <- function(n = NULL, prec = NULL, sd1, sd2 = NULL, cor, 
                            mean = NULL, conf_level = 0.95, 
                            ...){
    if (is.null(sd2)){
        sd2 <- sd1
    }
    if (is.null(mean)){
        mean <- 0
    }
    
    pdiff_sd <- sqrt(sd1^2 + sd2^2 - 2 * sd1 * sd2 * cor)
    out <- presize::prec_mean(mean = mean, sd = pdiff_sd, n = n, conf.level = conf_level, 
                                    conf.width = prec, ...)
    return(out)
}


#' @title Return a \code{presize} object with intervals back-transformed
#' @description This is a convenience function to get a log back-transformed 
#'     presize object to the original scale. 
#' @param presize_obj \code{presize}. An object generated by presize. 
#' @param ... Not used 
#' @export 
presize_log_backtransform <- function(presize_obj, ...){
    warning("Please do not report half-widhts if log-transformation was performed")
    names(presize_obj)[which(names(presize_obj) == "sd")] <- "sd_log"
    names(presize_obj)[which(names(presize_obj) == "mean")] <- "mean_log"
    presize_obj$lwr <- exp(presize_obj$lwr)
    presize_obj$upr <- exp(presize_obj$upr)
    presize_obj$conf.width <- presize_obj$upr - presize_obj$lwr
    presize_obj$mean_orig <- exp(presize_obj$mean_log)
    presize_obj$cv <- cv2sdlog(presize_obj$sd_log, inverse = TRUE)
    return(presize_obj)
}

#' @importFrom flextable as_flextable
#' @importFrom tibble tibble
#' @export
as_flextable.presize <- function(x, show, ...){
    Precision <- NULL
    show <- match.arg(show, c("half-width", "full-width"))
    
    lwr <- upr <- conf.width <- conf.level <- NULL
    tbl <- tibble::as_tibble(x)
    lookup <- c(`Conf. Width` = "conf.width", `Confidence Level` = "conf.level", 
                `Correlation` = "r", `Sample size` = "n", `Hypothetical Mean` = "mean", 
                `Std. Dev` = "sd", `Log Std. Dev` = "sd_log", `Log Mean` = "mean_log", 
                `Mean (Orig. Scale)` = "mean_orig", `Coeff. of Variation` = "cv")
    
    if (show == "half-width"){
        tbl <- tbl |> dplyr::mutate(`Precision` = conf.width/2) |>
            dplyr::relocate(`Precision`, .after = 2) |>
            dplyr::select(-conf.width)
    }
    tbl <- tbl |> 
        dplyr::mutate(`Interval` = paste0(round(lwr, 2), " , ", round(upr,2))) |>
        dplyr::rename(dplyr::any_of(lookup)) |> 
        dplyr::select(-c(lwr, upr)) 
    
    out <- tbl |> flextable::flextable() |> 
        flextable::autofit()
    return(out)
    
}


